services:
  web_application:
    build: .
    image: richieieie/task_tracker_web
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:17.2-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
volumes:
  postgres_data: