services:
  web_application:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:12345678@db:5432/todo_db
    depends_on:
      - db
  db:
    image: postgres:17.2-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=todo_db
volumes:
  postgres_data: